# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-20 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.TextField(null=True, unique=True, verbose_name='ID')),
                ('resturant_name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('resturant_address', models.CharField(db_index=True, max_length=500, verbose_name='Name')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='jersy_number')),
            ],
            options={
                'verbose_name': 'Resturants',
                'verbose_name_plural': 'Resturants',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resturant_comment', to='location.Resturant'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='st_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
